# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cá đá
email: saltysealion@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Wild Bettas in Australia
baseurl: "/anabantoids" # the subpath of your site, e.g. /blog
url: "http://saltysealion.github.io" # the base hostname & protocol for your site
twitter_username: saltysealion
github_username:  saltysealion

# Build settings
markdown: kramdown
